name: PHPUnit

on: pull_request

permissions:
  contents: read

concurrency:
  group: phpunit-32bits-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-32bits:
    runs-on: ubuntu-latest
    container: shivammathur/node:latest-i386

    strategy:
      matrix:
        php-versions: ['8.0']

    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, curl, dom, fileinfo, gd, imagick, intl, json, mbstring, oci8, openssl, pdo_sqlite, posix, sqlite, xml, zip, apcu
          tools: phpunit:9
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=autotest --database-pass=rootpassword --admin-user admin --admin-pass admin
          php -f index.php

      - name: PHPUnit
        working-directory: tests
        run: phpunit --configuration phpunit-autotest.xml
